import React from 'react';

const page = () => {
    return (
        <div className='container'>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
            <h1>About Page</h1>
        </div>
    );
};

export default page;